### ISSUE TITLE
Input ROM and Output ROM fields are swapped?

### ISSUE THREAD

**Issue by jeffyjeffy1023** [RetroHeim-Soft/dspatch-gui#1]
When I open the volume 1 rom by clicking on open file, the path goes in the output file box instead? (and vise versa)

**Comment by retroheim** [comment]
bruh what, lemme check that

**Comment by retroheim** [comment]
huh, that is an issue, sorry about that

**Comment by retroheim** [comment]
Thanks for telling me, turns out in my sleepy state a while back, I had flipped the text boxes around. Thanks for the headsup! I'll make a quick update and that should fix it.

**Comment by jeffyjeffy1023** [comment]
Thanks! :)

**Comment by retroheim** [comment]
no problem!
